### ISSUE TITLE
feature:  Paste to Json

### ISSUE THREAD

**Issue by enesfurkangenc** [Redoxahmii/json-to-ts.nvim#1]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

I like your plugin a lot but it needs some updates. It is very difficult to move from the json folder and then switch to the ts file and update the names of that file.

### Describe the solution you'd like

Instead you can convert the json I copied directly in the ts file

### Describe alternatives you've considered

Available as vscode plugin. 
https://marketplace.visualstudio.com/items?itemName=quicktype.quicktype

**Comment by redoxahmii** [comment]
Currently i am a little busy but i will look into adding this in a short while.

**Comment by redoxahmii** [comment]
@enesfurkangenc I have changed the name of the plugin from `json-to-ts.nvim` to `json-to-types.nvim` so i would suggest updating the name.
I tend to add support for more languages which is why i changed the name so just giving a reminder so you can change it in your config.

**Comment by redoxahmii** [comment]
@enesfurkangenc 
Sorry if this causes any inconvenience the plugin is still very small so i decided to change the name to something generalized for adding more langs. 
As for your request the neovim buffer API unfortunately is not good enough for changing types live as you edit the file.
Unfortunately this is going to specified as out of scope for this plugin.

**Comment by enesfurkangenc** [comment]
thank you for information i will follow this plugin 💯
